backend:
  name: git-gateway
  branch: master
media_folder: "assets/images/posts/"
logo_url: https://educate.infozy.tk/assets/images/logo.png
site_url: https://educate.infozy.tk
display_url: https://educate.infozy.tk
publish_mode: editorial_workflow
collections:
  - label: "Posts"
    name: "posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    extension: "md"
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss +0530"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Comments"
        name: "comments"
        widget: "hidden"
        default: true
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        hint: "This will be used across the pages and for search engines."
        widget: "string"
      - label: "Featured Image"
        name: "image"
        widget: "object"
        collapsed: true        
        fields:
          - label: "Give Image Source URL"
            name: "image"
            widget: "string"
            hint: "Give the Image Source Url or Scroll down to Upload Image"
          - label: "Upload Image"
            name: "image"
            widget: "image"
            hint: "Upload Image"
        required: false
        hint: "Give Source Image Url or Upload the Image !Important - Select only One Option"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Pages"
    name: "pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    extension: "md"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/{{slug}}/"
      - label: "Description"
        name: "description"
        hint: "This will be used as description for search engines."
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    delete: false
    files:
      - label: "Settings"
        name: "_config"
        file: "_config.yml"
        fields:
          - label: "Name"
            name: "name"
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Subtitle"
            name: "subtitle"
            widget: "string"
            hint: "Keep it Simple"
          - label: "Title of the Group"
            name: "group"
            widget: "string"
          - label: "URL of the Group"
            name: "group-url"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
            hint: "This will be used as description for search engines."
          - label: "Featured Image"
            name: "logo"
            widget: "object"
            collapsed: true        
            fields:
              - label: "Give Image Source URL"
                name: "logo"
                widget: "string"
                hint: "Give the Image Source Url or Scroll down to Upload Image"
              - label: "Upload Image"
                name: "logo"
                widget: "image"
                hint: "Upload Image"
            required: false
            hint: "Give Source Image Url or Upload the Image !Important - Select only One Option"
          - label: "Disqus Username"
            name: "disqus"
            widget: "string"
            hint: "Leave it blank if you don't want comments"
            required: false
          - label: "Posts per page"
            name: "paginate"
            widget: "number"
            valueType: "int"
            required: false
            hint: "Leave it blank if you don't want pagination"
          - label: "Thumbnail Height"
            name: "height_thumbnail"
            widget: "string"
            hint: "in px"
          - label: "Thumbnail Width"
            name: "width_thumbnail"
            widget: "string"
            hint: "in px"
          - label: "Post - Image Height"
            name: "height_post"
            widget: "string"
            hint: "in px"
          - label: "Post - Image Width"
            name: "width_post"
            widget: "string"
            hint: "in px"
          - label: "Home -HeroImage Height"
            name: "width_home_featured_thumbnail"
            widget: "string"
            hint: "in px"
          - label: "Home -HeroImage Width"
            name: "height_home_featured_thumbnail"
            widget: "string"
            hint: "in px"
          - label: "Turn on Auto Webp Conversion"
            name: "auto_webp_conversion"
            widget: "boolean"
            hint: "Either True or False"
          - label: "Lazy Image Loading"
            name: "lazyimages"
            widget: "select"
            options: 
              - label: "Enabled"
                value: "enabled"
              - label: "Disabled"
                value: "disabled"
          - label: "Base URL"
            name: "baseurl"
            widget: "string"
            hint: "The subpath of your site, e.g. /blog"
          - label: "URL"
            name: "siteurl"
            widget: "string"
            hint: "The base hostname and protocol for your site"
          - label: "Google Analytics ID"
            name: "analytics"
            widget: "string"
            required: false
